config/routes.rb
Lostandfound::Application.routes.draw do
  resources :categories
  resources :items do
    collection do 
      get 'search'
      get 'do_search'
    end

  end
  resources :posts

  

  root 'items#index'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :category
end

app/models/post.rb
class Post < ActiveRecord::Base
	def change
		create_table :posts do |t|
	    t.string :title
	    t.text :text
	 
	    t.timestamps
	  end
	end
end

app/models/something.rb
class Something < Type

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    clean_params = params.require(:category).permit(:title, :description)
    @category = Category.new(clean_params)
    if @category.save
        redirect_to @category, notice: 'category was successfully created.'
    else
      render action: 'new'
    end
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    item_params = params.require(:item).permit(:title, :description, :owner, :category)
    @item = Item.new(item_params)
    if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
    else
      render action: 'new'
    end
  end
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  def search
    @categories = Category.all.map {|c| [c.title, c.id]}
  end

  def do_search
    @items = []
      if params[:all_some] == '1'
        @items = Item.where(title: params[:title], description: params[:description], owner: params[:owner], category_id: params[:category_id])
        render :index
      else
        one = Item.where(title: params[:title], category_id: params[:category_id])
        two = Item.where(description: params[:description], category_id: params[:category_id])
        three = Item.where(owner: params[:owner], category_id: params[:category_id])
        @items = one + two + three
        render :index
      end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
	end

	def create
	  @post = Post.new(post_params)
	 
	  @post.save
	  redirect_to @post
	end

	def show
	  @post = Post.find(params[:id])
	end
	
	def index
	  @posts = Post.all
	end
	 
	private
	def post_params
	   params.require(:post).permit(:title, :text)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class = "row row-padding">
  <h1>Listing items</h1>
</div>
<div class = "row row-padding">
    <div class = "col-md-2"><h3>Title</h3></div>
    <div class = "col-md-3"><h3>Description</h3></div>
    <div class = "col-md-2"><h3>Owner</h3></div>
    <div class = "col-md-2"><h3>Category</h3></div>
  </div>

    <% @items.each do |item| %>
      <div class = "row row-padding">
        <div class = "col-md-2"><%= item.title %></div>
        <div class = "col-md-3"><%= item.description %></div>
        <div class = "col-md-2"><%= item.owner %></div>
        <div class = "col-md-2"><%= item.category_id %></div>
        <div class = "col-md-3">
          <%= link_to 'Show', item %> |
          <%= link_to 'Edit', edit_item_path(item) %> |
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
     </div>
    <% end %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
	<div class = "row header">
		<h1>Search Items Database</h1>
	</div>
<div class = "row">
	<div class="col-md-offset-1 col-md-4">
	  
	    <%= form_tag(do_search_items_path, method: "get", role: "form", class: "form") do %>
	      <div class="form-group">
	        <label class="control-label">And/Or:</label>
	        <%= select_tag(:all_some, options_for_select([['match all conditions', 1], ["match some", 2]]), class: "form-control") %>
	      </div>
	      <div class="form-group">
	        <label>Category:</label>
	        <%= select_tag(:category_id, options_for_select(@categories), class: "form-control") %>
	      </div>
	    </div>
	    <div class = "col-md-offset-1 col-md-5">
	      <div class="form-group">
	        <label>Title</label>
	        <%= text_field_tag(:title, "", class: "form-control") %>
	      </div>
	      
	      <div class="form-group">
	        <label>Description</label>
	        <%= text_field_tag(:description, "", class: "form-control") %>
	      </div>
	      
	      <div class="form-group">
	        <label>Owner</label>
	        <%= text_field_tag(:owner, "", class: "form-control") %>
	      </div>
	      <div >
	      	<%= submit_tag "Search", class: "btn btn-large" %>
	      	<span ></span>
	      </div>
	    <% end %>
	</div>
</div>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
<p>
  <strong>Owner:</strong>
  <%= @item.owner %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %> |
<%= link_to 'Search' search_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lostandfound</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css">
	<%= stylesheet_link_tag "custom" %>
	<script src="https://code.jquery.com/jquery.js"></script>
</head>
<body>
	<div class="container">
	 
	    <%= yield %>
	    <div class = "row footer row-padding">
			<%= link_to 'New Item', new_item_path, class: "btn" %> 	|
			<%= link_to 'Search', search_items_path, class: "btn" %>	|
			<%= link_to 'Items', items_path, class: "btn" %>
		</div>
	</div>

<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>

</body>
</html>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit "Post", class: "btn" %>
  </p>

  <%= link_to "My Blog", controller: "posts" %>
<% end %>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>
<%= link_to "My Blog", controller: "posts" %>